# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fetch/v1/fetch.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'fetch/v1/fetch.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from graph.v1 import graph_pb2 as graph_dot_v1_dot_graph__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66\x65tch/v1/fetch.proto\x12\x08\x66\x65tch.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x14graph/v1/graph.proto\"\xa6\x01\n\rSearchRequest\x12\x19\n\x08group_id\x18\x01 \x03(\tR\x07groupId\x12\x14\n\x05query\x18\x02 \x01(\tR\x05query\x12!\n\x0c\x63\x65ntral_node\x18\x03 \x01(\tR\x0b\x63\x65ntralNode\x12\x14\n\x05limit\x18\x04 \x01(\x05R\x05limit\x12+\n\x07\x66ilters\x18\x05 \x01(\x0b\x32\x11.fetch.v1.FiltersR\x07\x66ilters\"\x92\x02\n\x07\x46ilters\x12\x1f\n\x0bnode_labels\x18\x01 \x03(\tR\nnodeLabels\x12\x35\n\x08valid_at\x18\x02 \x03(\x0b\x32\x1a.fetch.v1.DateFilterGroupsR\x07validAt\x12\x39\n\ninvalid_at\x18\x03 \x03(\x0b\x32\x1a.fetch.v1.DateFilterGroupsR\tinvalidAt\x12\x39\n\ncreated_at\x18\x04 \x03(\x0b\x32\x1a.fetch.v1.DateFilterGroupsR\tcreatedAt\x12\x39\n\nexpired_at\x18\x05 \x03(\x0b\x32\x1a.fetch.v1.DateFilterGroupsR\texpiredAt\"B\n\x10\x44\x61teFilterGroups\x12.\n\x07\x66ilters\x18\x01 \x03(\x0b\x32\x14.fetch.v1.DateFilterR\x07\x66ilters\"m\n\nDateFilter\x12.\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x04\x64\x61te\x12/\n\x13\x63omparison_operator\x18\x02 \x01(\tR\x12\x63omparisonOperator\"U\n\x0eSearchResponse\x12\x19\n\x08group_id\x18\x01 \x01(\tR\x07groupId\x12(\n\x07results\x18\x02 \x03(\x0b\x32\x0e.graph.v1.EdgeR\x07results2M\n\x0c\x46\x65tchService\x12=\n\x06Search\x12\x17.fetch.v1.SearchRequest\x1a\x18.fetch.v1.SearchResponse\"\x00\x42\x34Z2github.com/enmand/alice/generated/fetch/v1;fetchv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fetch.v1.fetch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/enmand/alice/generated/fetch/v1;fetchv1'
  _globals['_SEARCHREQUEST']._serialized_start=90
  _globals['_SEARCHREQUEST']._serialized_end=256
  _globals['_FILTERS']._serialized_start=259
  _globals['_FILTERS']._serialized_end=533
  _globals['_DATEFILTERGROUPS']._serialized_start=535
  _globals['_DATEFILTERGROUPS']._serialized_end=601
  _globals['_DATEFILTER']._serialized_start=603
  _globals['_DATEFILTER']._serialized_end=712
  _globals['_SEARCHRESPONSE']._serialized_start=714
  _globals['_SEARCHRESPONSE']._serialized_end=799
  _globals['_FETCHSERVICE']._serialized_start=801
  _globals['_FETCHSERVICE']._serialized_end=878
# @@protoc_insertion_point(module_scope)
