# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from fetch.v1 import fetch_pb2 as fetch_dot_v1_dot_fetch__pb2


class FetchServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/fetch.v1.FetchService/Search',
                request_serializer=fetch_dot_v1_dot_fetch__pb2.SearchRequest.SerializeToString,
                response_deserializer=fetch_dot_v1_dot_fetch__pb2.SearchResponse.FromString,
                _registered_method=True)


class FetchServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FetchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=fetch_dot_v1_dot_fetch__pb2.SearchRequest.FromString,
                    response_serializer=fetch_dot_v1_dot_fetch__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fetch.v1.FetchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fetch.v1.FetchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FetchService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fetch.v1.FetchService/Search',
            fetch_dot_v1_dot_fetch__pb2.SearchRequest.SerializeToString,
            fetch_dot_v1_dot_fetch__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
